#version 450

layout (local_size_x = 32, local_size_y = 8) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform image2D resultImage;

void main()
{
    vec3 color = imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy)).rgb;
    vec4 res = vec4(color,1.0);// imageLoad(inputImage, ivec2(gl_GlobalInvocationID.xy))
    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy),res); 	
}
